version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     
      - "15672:15672"    
    environment:
      RABBITMQ_DEFAULT_USER: appuser
      RABBITMQ_DEFAULT_PASS: appassword
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1200:1433"      
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - app-network

  api:
    build: .
    container_name: api
    ports:
      - "5200:8080"                   
    environment:
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Username=appuser
      - RabbitMQ__Password=appassword
      - RabbitMQ__QueueName=order.process
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=OrderDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
    depends_on:
      - rabbitmq
      - sqlserver
    networks:
      - app-network

  microservice:
    build: ../ProcessOrder 
    container_name: microservice
    ports:
      - "6000:6000"                        
    environment:
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Username=appuser
      - RabbitMQ__Password=appassword
      - RabbitMQ__QueueName=order.process
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=OrderDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
    depends_on:
      - rabbitmq
      - sqlserver
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sql_data:
